#!/bin/bash
set -eu -o pipefail

if [ $# -ne 3 ]
then
  echo "$0 <config.sh> {high|low} <output.mp4>" >&2
  exit 2
fi

CFG=$1
RES=$2
OUT=$3
shift 2

source "$CFG"

case "$RES" in
  "high")
    STRM=11
  ;;
  "low")
    STRM=12
  ;;
  *)
    exec "$0" --help
  ;;
esac

exec vlc \
  --intf dummy \
  --sout="#standard{access=file,mux=mp4,dst=$OUT}" \
  --network-caching=200 \
  --rtsp-user="$USERNAME" \
  --rtsp-pwd="$PASSWORD" \
  "rtsp://eyeofthebeholder-wifi/$STRM"
